# Generated by Django 5.0.7 on 2024-11-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_remove_hojadevida_cv_file_hojadevida_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojadevida',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='hojas_de_vida/'),
        ),
    ]
