# Generated by Django 5.0.7 on 2024-11-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HojaDeVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('archivo_cv', models.FileField(blank=True, null=True, upload_to='cv_files/')),
                ('imagen_cv', models.ImageField(blank=True, null=True, upload_to='cv_images/')),
            ],
        ),
    ]
